version: '2'
services:
  web:
      image: nginx:latest
      ports:
          - "8080:80"
      volumes:
          # - ./code:/code
          - /home/dmitry/host/magento.dev:/code
          - ./site.conf:/etc/nginx/conf.d/default.conf
          - ./log:/var/log/nginx
      links:
          - php
  php:
      build:
          context: ./php
      volumes:
          # - ./code:/code
          - /home/dmitry/host/magento.dev:/code
      links:
          - mysql:mysql
      environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=test
  mysql:
      image: mariadb
      environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=test
      volumes:
          - ./database:/var/lib/mysql