version: '2'
services:
    web:
      image: nginx:latest
      ports:
        - "8080:80"
      volumes:
        - ./code:/code
        - ./site.conf:/etc/nginx/conf.d/default.conf
        # - ./log:/var/log/nginx
      links:
        - php
    php:
      build:
        context: ./php
      volumes:
        - ./code:/code
      links:
        - mysql:mysql
    mysql:
      image: mariadb:latest
      env_file:
          - ./.env
      environment:
          - MYSQL_DATABASE=${MYSQL_DATABASE}
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      volumes:
        - ./database:/var/lib/mysql