version: '2'
services:
    web:
      image: nginx:latest
      ports:
        - "8080:80"
      volumes:
        - ./code:/code
        - ./conf.d:/etc/nginx/conf.d
        # - ./log:/var/log/nginx
      depends_on:
        - php
        - mysql
    php:
      build:
        context: ./php
      volumes:
        - ./code:/code
    mysql:
      image: mariadb:latest
      env_file:
          - ./.env
      environment:
          - MYSQL_DATABASE=${MYSQL_DATABASE}
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      volumes:
        - ./database:/var/lib/mysql
      ports:
        - "3301:3306"